### ISSUE TITLE
Misspelling & Gist (?)

### ISSUE THREAD

**Issue by snunez1** [ccqpein/Github-API-CL#2]
You've got a misspelling in the github project description.

Also, this would be a good start for gists. cl-gist has been abandoned. Any plans for gists?

**Comment by ccqpein** [comment]
@snunez1 Just fix the misspelling in the description. Nice catch. 

Also, I even don't use gist a lot. But it sounds like a good start to a new project. Let me check what `cl-gist` was doing.

**Comment by ccqpein** [comment]
I give the keyword `:content` to the `github-api-call` method to send the body through API. It can use to gist.
